### ISSUE TITLE
Issue with timescale volume path?

### ISSUE THREAD

**Issue by trevjonez** [codecov/self-hosted#32]
https://github.com/codecov/self-hosted/blob/e50fa23e3c7101a1a93bb367540e404eb218c660/docker-compose.yml#L89
[The timescale docs indicate two different paths based on the image type used.](
https://docs.timescale.com/self-hosted/latest/install/installation-docker/#:~:text=The%20two%20container%20types%20store%20PostgreSQL%20data%20dir%20in%20different%20places%2C%20make%20sure%20you%20select%20the%20correct%20one%20to%20mount%3A)

![image](https://github.com/codecov/self-hosted/assets/5386503/c5e5a95c-ec7c-4e19-9f10-984e729e1c9e)

**Comment by imnotjames** [comment]
Same issue here
